### ISSUE TITLE
Docker push fails 

### ISSUE THREAD

**Issue by sanjanrahman** [jfrog/jfrog-pipelines-docker-sample#2]
DockerPush
[DockerPush] Authenticating with integration: art

[Info] Encrypting password...
Restoring state files
Files restored

[DockerPush] Pushing image sanjanrahman.jfrog.io/docker-local/dbp:46 to repository docker-local
Error response from daemon: Get https://sanjanrahman.jfrog.io/v2/: unauthorized: BAD_CREDENTIAL
Error response from daemon: Get https://sanjanrahman.jfrog.io/v2/: unknown: This request is blocked due to recurrent login failures, please try again in 2 seconds
[Error] Docker login failed for: sanjanrahman.jfrog.io/docker-local, sanjanrahman.jfrog.io.
Docker image must be in the form: docker-registry-domain/path-in-repository/image-name:version. exit status 1

**Comment by sanjanrahman** [comment]
Art creds url is  https://sanjanrahman.jfrog.io and the build steps is success

**Comment by sanjanrahman** [comment]
Did all the steps mentioned

**Comment by douglasawh** [comment]
This was closed without any comment. How was this fixed? Did you need to change the password in Artifactory?
